name: Deploy to InfinityFree via FTP

on:
  push:
    branches:
      - main  # 当 main 分支有更新时触发，如果你的主分支叫 master 请改为 master

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: Sync files to InfinityFree
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./  # 部署本地哪个目录，./ 代表整个项目
        server-dir: /htdocs/  # 必须传到 InfinityFree 的 htdocs 文件夹下

